[package]
name = "moduleName"
version = "1.0.0"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/nft_protocol"

[dependencies.Permissions]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/permissions"

[dependencies.LiquidityLayer]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/liquidity_layer"

[dependencies.Allowlist]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/allowlist"

[dependencies.Authlist]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/authlist"

[dependencies.Kiosk]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/kiosk"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/launchpad"

[dependencies.Utils]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b2b7a41eb4a24fb486071c9f810f0a0a487848a7"
subdir = "contracts/utils"

[addresses]
sui =  "0x2"
module_name = "0x0"
module_creator_placeholder = "0x0"
