[package]
name = "{{ name_no_space }}"
version = "0.0.1"

[dependencies.NftProtocol]
git = "https://github.com/ReleapIO/sui-nft-protocol.git"
rev = "testnet"

[addresses]
sui =  "0x2"
{{ name_lower_no_space }} = "0x0"
